spring.application.name=Reddit Message Manager
debug=true
# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/reddit_messages
spring.datasource.username=root
spring.datasource.password=root@1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Server Configuration
server.port=8080

# Reddit API Configuration
reddit.client.id=M9IRnasjoRFskVNj180eZA
reddit.client.secret=XDuQGOZ2yzaQoOaSKyAOguMkaWt6Cg
reddit.redirect.uri=http://localhost:8080/auth/callback
